// v4.6: Monitor Template Library
// Prednastavljeni monitorji za običajne scenarije.
// Vsak template je povsem konfiguriran (source, URL, filters, prompt, tags).

export type Source = 'bolha' | 'nepremicnine' | 'avtonet' | 'salomon' | 'vinted' | 'custom-rss' | 'mobile-de' | 'kleinanzeigen' | 'subito' | 'willhaben';

export interface MonitorTemplate {
  id: string;
  name: string;
  description: string;
  category: 'elektronika' | 'avto' | 'nepremicnine' | 'moda' | 'orodje' | 'sport' | 'drugo';
  source: Source;
  sourceUrl: string;
  keywords: string;
  excludeKeywords: string;
  minPrice: number | null;
  maxPrice: number | null;
  intervalMinutes: number;
  customPrompt: string;
  tags: string;
  icon: string; // emoji
}

export const MONITOR_TEMPLATES: MonitorTemplate[] = [
  // ===== ELEKTRONIKA =====
  {
    id: 'tpl-iphone-13-pro',
    name: 'iPhone 13 Pro — Bolha',
    description: 'iPhone 13 Pro na Bolhi, cene do 500€. AI pazi na stanje in embalažo.',
    category: 'elektronika',
    source: 'bolha',
    sourceUrl: 'https://www.bolha.com/index.php?ctl=search&A_3_1=iphone+13+pro&A_12_1=1&A_0_1=0&sort=new',
    keywords: 'iphone 13 pro',
    excludeKeywords: 'case,maska,ekran,zascitnik,baterija,zamenjava,poplavljeno,pokvarjen',
    minPrice: 200,
    maxPrice: 500,
    intervalMinutes: 15,
    customPrompt: 'Posebej pazi na oglase, ki vsebujejo "nujna prodaja", "selim se", "rabim denar" — pogosto so podcenjeni. Preveri ali je omenjen original polnilec in embalaža. Sumljivo če cena pod 250€.',
    tags: 'elektronika,iphone,bolha',
    icon: '📱',
  },
  {
    id: 'tpl-macbook-pro-m1',
    name: 'MacBook Pro M1 — Bolha',
    description: 'MacBook Pro M1 13"/14", do 1000€. Pazi na baterijo in zanka.',
    category: 'elektronika',
    source: 'bolha',
    sourceUrl: 'https://www.bolha.com/index.php?ctl=search&A_3_1=macbook+pro+m1&A_12_1=1&A_0_1=0&sort=new',
    keywords: 'macbook pro,m1',
    excludeKeywords: 'case,torbica,nalagalnik,zascitnik,tipkovnica,miska',
    minPrice: 600,
    maxPrice: 1000,
    intervalMinutes: 20,
    customPrompt: 'Preveri število ciklov baterije (idealno <300). Pazi na zanka (AppleCare). Sumnjivo če prodajalec noče pokazati sistema in logov.',
    tags: 'elektronika,macbook,bolha',
    icon: '💻',
  },
  {
    id: 'tpl-ps5-bolha',
    name: 'PlayStation 5 — Bolha',
    description: 'PS5 konzole z ali brez iger, do 500€.',
    category: 'elektronika',
    source: 'bolha',
    sourceUrl: 'https://www.bolha.com/index.php?ctl=search&A_3_1=playstation+5&A_12_1=1&A_0_1=0&sort=new',
    keywords: 'ps5,playstation 5',
    excludeKeywords: 'case,držalo,kabel,usb,controller,stikalo',
    minPrice: 300,
    maxPrice: 500,
    intervalMinutes: 15,
    customPrompt: 'Preveri ali je omenjena original škatla in kabel. Pazi na razliko med PS5 in PS5 Digital. Sumnjivo če cena pod 350€.',
    tags: 'elektronika,gaming,bolha',
    icon: '🎮',
  },

  // ===== AVTO =====
  {
    id: 'tpl-golf-mk6',
    name: 'VW Golf MK6 — Avtonet',
    description: 'Golf 6, do 6000€, letnik 2008-2012. Idealno za mlade voznike.',
    category: 'avto',
    source: 'avtonet',
    sourceUrl: 'https://www.avto.net/adresults.asp?znamka=VOLKSWAGEN&model=GOLF&cenaMIN=0&cenaMAX=6000',
    keywords: 'golf',
    excludeKeywords: 'golf 7,golf 5,golf 4',
    minPrice: 3000,
    maxPrice: 6000,
    intervalMinutes: 30,
    customPrompt: 'Pazi na servisno zgodovino. Zadnji servis mora biti nedaven. Preveri STD (servisni interval) in stanje zavor. Sumljivo če "samo zamenjava" ali "nujno" brez utemeljitve.',
    tags: 'avto,golf,avtonet',
    icon: '🚗',
  },
  {
    id: 'tpl-a3-8l',
    name: 'Audi A3 8L — Avtonet',
    description: 'Audi A3 8L (1996-2003), do 3000€. Klubski avto.',
    category: 'avto',
    source: 'avtonet',
    sourceUrl: 'https://www.avto.net/adresults.asp?znamka=AUDI&model=A3&cenaMIN=0&cenaMAX=3000',
    keywords: 'a3',
    excludeKeywords: 'a4,a6,a3 8p',
    minPrice: 1000,
    maxPrice: 3000,
    intervalMinutes: 60,
    customPrompt: 'Starejši avto — preveri rjo, stanje motorja (1.6 ali 1.8T so zanesljivi). Pazi na "nujno prodaja" in dokaze o lastništvu. Pazljivo z "zamenjava".',
    tags: 'avto,audi,avtonet,klubski',
    icon: '🚙',
  },
  {
    id: 'tpl-yaris-hybrid',
    name: 'Toyota Yaris Hybrid — Avtonet',
    description: 'Yaris Hybrid (2012+), do 9000€. Idealno za mesto.',
    category: 'avto',
    source: 'avtonet',
    sourceUrl: 'https://www.avto.net/adresults.asp?znamka=TOYOTA&model=YARIS&cenaMIN=5000&cenaMAX=9000',
    keywords: 'yaris,hybrid',
    excludeKeywords: '',
    minPrice: 5000,
    maxPrice: 9000,
    intervalMinutes: 30,
    customPrompt: 'Hybrid baterija naj bo original in brez napak (preveri SSE). Pazi na razliko med 1.5 in 1.0 (samo 1.5 je hybrid). Letnik 2012+ je bolj zanesljiv.',
    tags: 'avto,toyota,hybrid,mesto',
    icon: '🚘',
  },

  // ===== NEPREMIČNINE =====
  {
    id: 'tpl-2sob-lj',
    name: '2-sobno LJ mesto — Nepremičnine',
    description: '2-sobna stanovanja v Ljubljani, do 200k. RSS vir.',
    category: 'nepremicnine',
    source: 'nepremicnine',
    sourceUrl: 'https://www.nepremicnine.net/oglasi-prodaja/ljubljana-mesto/stanovanje/2-sobno/cena-od-1-do-200-tisoč-evrov/?output=rss',
    keywords: '',
    excludeKeywords: 'podnajem,običajna,delitev',
    minPrice: 50000,
    maxPrice: 200000,
    intervalMinutes: 60,
    customPrompt: 'Pazi na lokacijo (okolica centra je dražja ampak boljša). Preveri energijski razred (A/B so dražji ampak cenejši na dolgi rok). Sumljivo če pod 80k brez utemeljitve.',
    tags: 'nepremicnine,ljubljana,investicija',
    icon: '🏢',
  },
  {
    id: 'tpl-hisa-bela-krajina',
    name: 'Hiša Bela krajina — Nepremičnine',
    description: 'Hiše v Beli krajini, do 150k. Za umik iz mesta.',
    category: 'nepremicnine',
    source: 'nepremicnine',
    sourceUrl: 'https://www.nepremicnine.net/oglasi-prodaja/bela-krajina/hisa/?output=rss',
    keywords: '',
    excludeKeywords: '',
    minPrice: 30000,
    maxPrice: 150000,
    intervalMinutes: 120,
    customPrompt: 'Preveri stanje strehe in instalacij. Pazi na hiše, ki potrebujejo obnovo (lahko so dober deal). Lokacija: Črnomelj, Metlika, Semič so bolj zanesljive.',
    tags: 'nepremicnine,bela-krajina,hisa',
    icon: '🏠',
  },
  {
    id: 'tpl-garaza-lj',
    name: 'Garaža LJ — Nepremičnine',
    description: 'Garaže v Ljubljani, do 25k. Solidna investicija.',
    category: 'nepremicnine',
    source: 'nepremicnine',
    sourceUrl: 'https://www.nepremicnine.net/oglasi-prodaja/ljubljana-mesto/garaza/?output=rss',
    keywords: 'garaza',
    excludeKeywords: 'parkirno mesto',
    minPrice: 8000,
    maxPrice: 25000,
    intervalMinutes: 60,
    customPrompt: 'Preveri legalnost (ali ima garaža lastništvo ali je samo najem zemljišča). Pazi na velikost — standardna garaža naj bi bila vsaj 12m².',
    tags: 'nepremicnine,ljubljana,garaza,investicija',
    icon: '🅿️',
  },

  // ===== MODA =====
  {
    id: 'tpl-nike-air-max-vinted',
    name: 'Nike Air Max — Vinted',
    description: 'Nike Air Max na Vinted, do 80€. Pazi na pristnost.',
    category: 'moda',
    source: 'vinted',
    sourceUrl: 'https://www.vinted.si/api/v2/catalog/items?search_text=nike%20air%20max&order_by=newest_first',
    keywords: 'nike,air max',
    excludeKeywords: '',
    minPrice: 20,
    maxPrice: 80,
    intervalMinutes: 30,
    customPrompt: 'Preveri pristnost — šivi, embalaža, logotip. Sumljivo če pod 30€ za nove. Pazi na velikost in stanje.',
    tags: 'moda,nike,vinted',
    icon: '👟',
  },
  {
    id: 'tpl-levis-501-vinted',
    name: 'Levi\'s 501 — Vinted',
    description: 'Levi\'s 501 jeans na Vinted, do 50€.',
    category: 'moda',
    source: 'vinted',
    sourceUrl: 'https://www.vinted.si/api/v2/catalog/items?search_text=levis%20501&order_by=newest_first',
    keywords: 'levis,501',
    excludeKeywords: '',
    minPrice: 15,
    maxPrice: 50,
    intervalMinutes: 45,
    customPrompt: 'Preveri pristnost — zadnja značka, notranje oznake. Pazi na velikost in dolžino. Original 501 imajo značilno rdečo zastavico na zadnjem žepu.',
    tags: 'moda,levis,vinted',
    icon: '👖',
  },

  // ===== ORODJE =====
  {
    id: 'tpl-bosch-orodje-bolha',
    name: 'Bosch orodje — Bolha',
    description: 'Bosch profesionalno orodje, do 200€.',
    category: 'orodje',
    source: 'bolha',
    sourceUrl: 'https://www.bolha.com/orodja?query=bosch',
    keywords: 'bosch',
    excludeKeywords: 'rezervni,del,nadomestek',
    minPrice: 30,
    maxPrice: 200,
    intervalMinutes: 60,
    customPrompt: 'Preveri stanje baterij (pri cordless). Pazi na razliko med zelenim (DIY) in modrim (Professional) Bosch. Original polnilci in kovček so plus.',
    tags: 'orodje,bosch,bolha',
    icon: '🔧',
  },
  {
    id: 'tpl-makita-orodje-bolha',
    name: 'Makita orodje — Bolha',
    description: 'Makita profesionalno orodje, do 300€.',
    category: 'orodje',
    source: 'bolha',
    sourceUrl: 'https://www.bolha.com/orodja?query=makita',
    keywords: 'makita',
    excludeKeywords: 'rezervni,del',
    minPrice: 50,
    maxPrice: 300,
    intervalMinutes: 60,
    customPrompt: 'Makita 18V LXT serija je najboljša. Preveri število ciklov baterij. Pazi na razliko med original in kit ponaredki (kit ponaredki so cenejši ampak manj zanesljivi).',
    tags: 'orodje,makita,bolha',
    icon: '🛠️',
  },

  // ===== SPORT =====
  {
    id: 'tpl-golf-oprema-bolha',
    name: 'Golf oprema — Bolha',
    description: 'Golf palice in oprema, do 400€.',
    category: 'sport',
    source: 'bolha',
    sourceUrl: 'https://www.bolha.com/sport?query=golf%20palice',
    keywords: 'golf,palica,železo,driver',
    excludeKeywords: '',
    minPrice: 50,
    maxPrice: 400,
    intervalMinutes: 90,
    customPrompt: 'Preveri komplet (koliko palic, kateri znamki). Pazi na starost —Titelist, Callaway, TaylorMade so top znamke. Set mora imeti vsaj driver, železa 4-PW, putter.',
    tags: 'sport,golf,bolha',
    icon: '⛳',
  },
  {
    id: 'tpl-smuci-bolha',
    name: 'Smuči — Bolha',
    description: 'Smuči in vezmi, do 250€.',
    category: 'sport',
    source: 'bolha',
    sourceUrl: 'https://www.bolha.com/sport?query=smuči',
    keywords: 'smuči,smuci,vezni',
    excludeKeywords: '',
    minPrice: 30,
    maxPrice: 250,
    intervalMinutes: 90,
    customPrompt: 'Preveri stanje drsne površine in robnikov. Pazi na starost smuči (starejše od 5 let imajo manj vrednost). Znamke: Rossignol, Atomic, Salomon, Head.',
    tags: 'sport,smuci,bolha',
    icon: '⛷️',
  },

  // ===== DRUGO =====
  {
    id: 'tpl-kolo-bolha',
    name: 'Kolo — Bolha',
    description: 'Kolesa (MTB/cestna), do 600€.',
    category: 'drugo',
    source: 'bolha',
    sourceUrl: 'https://www.bolha.com/kolesa?query=kolo',
    keywords: '',
    excludeKeywords: 'kolesar,del,reze',
    minPrice: 100,
    maxPrice: 600,
    intervalMinutes: 60,
    customPrompt: 'Preveri okvir (razpoke), stanje prestav (Shimano/SRAM), zavor in verige. Pazi na velikost okvirja. Sumljivo če kolo nima serijske številke.',
    tags: 'kolo,bolha,sport',
    icon: '🚴',
  },
  {
    id: 'tpl-rtv-bolha',
    name: 'RTV komponente — Bolha',
    description: 'Zvočniki, ojačevalci, predpojačevalci, do 500€.',
    category: 'elektronika',
    source: 'bolha',
    sourceUrl: 'https://www.bolha.com/elektronika?query=zvocniki',
    keywords: 'zvocnik,ojačevalec,amplifier',
    excludeKeywords: 'kabel,priključek',
    minPrice: 50,
    maxPrice: 500,
    intervalMinutes: 60,
    customPrompt: 'Preveri stanje membran in tuljav. Pazi na znamke: Bowers&Wilkins, KEF, Dynaudio, NAD, Marantz, Yamaha. Vintage ponavadi cenejše ampak boljše kvalitete.',
    tags: 'elektronika,rtv,bolha,audio',
    icon: '🔊',
  },

  // ===== MOBILE.DE (v6.17) — nemški trg za cross-border arbitražo =====
  // Nemški avtomobili so običajno 10-20% cenejši kot v Sloveniji.
  // Shipping do SI: 300-500€. Znotraj EU carina enostavna.
  // Strategija: kupi v DE, prodaj v SI.
  {
    id: 'tpl-mobile-de-bmw-3',
    name: 'BMW Series 3 — Mobile.de (DE→SI arbitraža)',
    description: 'BMW 3 (E90/F30) do 10.000€ v DE. Cross-border: kupi DE, prodaj SI. Prihranek 10-20%.',
    category: 'avto',
    source: 'mobile-de',
    sourceUrl: 'https://suchen.mobile.de/fahrzeuge/search.html?dam=false&isSearchRequest=true&make=BMW&model=SERIES_3&priceTo=10000&sortOption=price.asc',
    keywords: 'bmw,320,330,318,320d,330d',
    excludeKeywords: 'm3,sport,line,racing',
    minPrice: 3000,
    maxPrice: 10000,
    intervalMinutes: 60,
    customPrompt: 'CROSS-BORDER ARBITRAŽA: nemški avto cenejši 10-20% od SI. Preveri: VIN (vincheck.de), servisna zgodovina (Scheckheft), število lastnikov, NAPAKA v naslovu pomeni "poškodovan". Shipping DE→SI ~400€. Prihranek: če je cena v DE 7000€ in bi v SI stal 9000€, dobiček ~1600€ po stroških. Sumljivo: "unfallfrei" (brez nesreče) mora biti izrecno navedeno, drugače je avto verjetno poškodovan.',
    tags: 'avto,bmw,mobile-de,cross-border,arbitraza',
    icon: '🚗',
  },
  {
    id: 'tpl-mobile-de-audi-a4',
    name: 'Audi A4 — Mobile.de (DE→SI arbitraža)',
    description: 'Audi A4 B8/B9 do 12.000€ v DE. Premium avto, dobro se prodaja v SI.',
    category: 'avto',
    source: 'mobile-de',
    sourceUrl: 'https://suchen.mobile.de/fahrzeuge/search.html?dam=false&isSearchRequest=true&make=AUDI&model=A4&priceTo=12000&sortOption=price.asc',
    keywords: 'audi,a4,2.0,tdi',
    excludeKeywords: 'rs4,s4,quattro',
    minPrice: 4000,
    maxPrice: 12000,
    intervalMinutes: 60,
    customPrompt: 'CROSS-BORDER: Audi A4 je v SI zelo iskan. V DE cenejši za ~15%. Pazi na: TDI motor (bolj zaželen v SI), avtomatski menjalnik (S-tronic — preveri zadnjo službo), letnik >2008 (B8 generacija). "Scheckheftgepflegt" = servisno voden. Sumnjivo: cene pod 5000€ za letnik >2010.',
    tags: 'avto,audi,mobile-de,cross-border,arbitraza',
    icon: '🚗',
  },
  {
    id: 'tpl-mobile-de-vw-golf-7',
    name: 'VW Golf 7 — Mobile.de (DE→SI arbitraža)',
    description: 'VW Golf 7 (2012-2017) do 10.000€ v DE. Najbolj prodajan avto v SI.',
    category: 'avto',
    source: 'mobile-de',
    sourceUrl: 'https://suchen.mobile.de/fahrzeuge/search.html?dam=false&isSearchRequest=true&make=VOLKSWAGEN&model=GOLF&priceTo=10000&yearFrom=2012&sortOption=price.asc',
    keywords: 'golf,1.6,2.0,tdi,gti',
    excludeKeywords: 'golf 8,golf 6,variant',
    minPrice: 5000,
    maxPrice: 10000,
    intervalMinutes: 45,
    customPrompt: 'CROSS-BORDER: Golf 7 je v SI zelo prodajan. V DE ~15% cenejši. Pazi na: 1.6 TDI (najbolj ekonomičen), DSG menjalnik (preveri servis), letnik >2014 (boljši motorji). "Erstzulassung" = prva registracija. Prihranek: 7000€ v DE = ~9000€ v SI = ~1600€ dobička po stroških.',
    tags: 'avto,vw,golf,mobile-de,cross-border,arbitraza',
    icon: '🚗',
  },
  {
    id: 'tpl-mobile-de-mercedes-c',
    name: 'Mercedes C-Class — Mobile.de (DE→SI arbitraža)',
    description: 'Mercedes C-razred W204/W205 do 13.000€ v DE. Premium, dobro se prodaja v SI.',
    category: 'avto',
    source: 'mobile-de',
    sourceUrl: 'https://suchen.mobile.de/fahrzeuge/search.html?dam=false&isSearchRequest=true&make=MERCEDES-BENZ&model=C_CLASS&priceTo=13000&sortOption=price.asc',
    keywords: 'mercedes,c180,c200,c220,cdi',
    excludeKeywords: 'c63,amg,brabus',
    minPrice: 5000,
    maxPrice: 13000,
    intervalMinutes: 60,
    customPrompt: 'CROSS-BORDER: Mercedes C-razred premium avto. V DE ~12% cenejši. Pazi na: CDI motor (bolj zanesljiv), W205 (2014+) je bolj moderen, servisna zgodovina pri Mercedes centru (zelo pomembno!). "Unfallfrei" obvezno. Preveri: ZM (zobni menjalnik) in pakete (Avantgarde, Elegance).',
    tags: 'avto,mercedes,mobile-de,cross-border,arbitraza',
    icon: '🚗',
  },
  {
    id: 'tpl-mobile-de-elektro',
    name: 'Električni avtomobili — Mobile.de (DE→SI)',
    description: 'EV avtomobili do 20.000€ v DE. Slovenska subvencija 4500€ za EV!',
    category: 'avto',
    source: 'mobile-de',
    sourceUrl: 'https://suchen.mobile.de/fahrzeuge/search.html?dam=false&isSearchRequest=true&fuel=ELECTRIC&priceTo=20000&sortOption=price.asc',
    keywords: 'electric,elektro,tesla,nissan,leaf,zoe,kona,i3',
    excludeKeywords: 'hibrid,plug-in',
    minPrice: 8000,
    maxPrice: 20000,
    intervalMinutes: 90,
    customPrompt: 'CROSS-BORDER + SUBVENCIJA: Slovenija daje 4500€ subvencije za EV! To pomeni: avto za 18000€ v DE + 400€ shipping - 4500€ subvencija = efektivno 13900€. Če ga prodaš za 18000€ v SI, dobiček ~4100€. Pazi na: kapaciteta baterije (SOH >85%), Nissan Leaf (bolj zanesljiv), Renault Zoe (malo baterije). Preveri polnilnik (Type 2, CCS).',
    tags: 'avto,elektro,ev,mobile-de,cross-border,subvencija',
    icon: '⚡',
  },

  // ===== v6.18: KLEINANZEIGEN.DE (Nemčija — največji generalni oglasnik) =====
  // 10-20% cenejše za elektroniko in pohištvo. Shipping do SI: 10-15€ (manjše stvari).
  {
    id: 'tpl-kleinanzeigen-iphone',
    name: 'iPhone 13/14 Pro — Kleinanzeigen (DE→SI)',
    description: 'iPhone 13/14 Pro v DE, do 600€. V SI 700-800€. Cross-border dobiček ~100-150€/kos.',
    category: 'elektronika',
    source: 'kleinanzeigen',
    sourceUrl: 'https://www.kleinanzeigen.de/s-suchanfrage.html?keywords=iphone+13+pro&priceType:from=300&priceType:to=600',
    keywords: 'iphone 13,iphone 14,pro',
    excludeKeywords: 'case,panzerglas,reparatur,defekt,ersatzteil',
    minPrice: 300,
    maxPrice: 600,
    intervalMinutes: 30,
    customPrompt: 'CROSS-BORDER ARBITRAŽA: iPhone v DE ~15% cenejši kot v SI. Shipping DHL ~12€. Preveri: "Ohne iCloud Sperre" (brez iCloud zaklepa — obvezno!), "Akku" (baterija — preveri kapaciteto), "Originalverpackung" (original embalaža). Sumnjivo: "Defekt", "Reparaturbedürftig", "Ersatzteil". Vklopi "versand" filter da najdeš samo oglase s shipping.',
    tags: 'elektronika,iphone,kleinanzeigen,cross-border,de',
    icon: '📱',
  },
  {
    id: 'tpl-kleinanzeigen-macbook',
    name: 'MacBook Pro/Air M1/M2 — Kleinanzeigen (DE→SI)',
    description: 'MacBook M1/M2 v DE, do 1000€. V SI 1200-1400€. Dobiček ~200€/kos.',
    category: 'elektronika',
    source: 'kleinanzeigen',
    sourceUrl: 'https://www.kleinanzeigen.de/s-suchanfrage.html?keywords=macbook+pro+m1&priceType:from=600&priceType:to=1000',
    keywords: 'macbook pro,m1,m2,air',
    excludeKeywords: 'case,schutzhülle,netzteil,lader,defekt',
    minPrice: 600,
    maxPrice: 1000,
    intervalMinutes: 45,
    customPrompt: 'CROSS-BORDER: MacBook M1/M2 v DE ~20% cenejši. Shipping ~15€. Preveri: "Zustand" (stanje — "Sehr gut" najboljše), "Akku Zyklen" (cikli baterije <300 idealno), "Garantie" (garancija), "AppleCare". Sumnjivo: cene pod 700€ za M1 Pro. Pazi na M1 vs M2 (M2 dražji).',
    tags: 'elektronika,macbook,kleinanzeigen,cross-border,de',
    icon: '💻',
  },
  {
    id: 'tpl-kleinanzeigen-playstation',
    name: 'PlayStation 5 — Kleinanzeigen (DE→SI)',
    description: 'PS5 v DE, do 400€. V SI 450-500€. Dobiček ~70€/kos, volumen prodaje.',
    category: 'elektronika',
    source: 'kleinanzeigen',
    sourceUrl: 'https://www.kleinanzeigen.de/s-suchanfrage.html?keywords=playstation+5&priceType:from=300&priceType:to=400',
    keywords: 'playstation 5,ps5',
    excludeKeywords: 'case,controller,spiel,game,zubehör,defekt',
    minPrice: 300,
    maxPrice: 400,
    intervalMinutes: 20,
    customPrompt: 'CROSS-BORDER: PS5 v DE ~10% cenejši. Shipping ~10€ (DHL paket). Preveri: "Originalverpackung" (škatla), "Controller" (1 ali 2?), "Kabel" (HDMI/napajalnik). Pazi na razliko med PS5 in PS5 Digital Edition (Digital cenejši). Sumnjivo: cene pod 320€.',
    tags: 'elektronika,gaming,playstation,kleinanzeigen,cross-border,de',
    icon: '🎮',
  },

  // ===== SUBITO.IT (Italija — največji italijanski oglasnik) =====
  // 10-15% cenejše za oblačila in modne dodatke. Shipping do SI: 15-20€.
  {
    id: 'tpl-subito-luxury-bags',
    name: 'Luxury torbe (Gucci, Prada) — Subito (IT→SI)',
    description: 'Italijanske luxury torbe (Gucci, Prada, Versace) v IT do 500€. V SI 700-1000€.',
    category: 'moda',
    source: 'subito',
    sourceUrl: 'https://www.subito.it/annunci-italia/vendita?q=gucci+borsa&prezzo=200-500',
    keywords: 'gucci,prada,versace,fendi,borsa',
    excludeKeywords: 'usato,rovinato,replica,falso',
    minPrice: 200,
    maxPrice: 500,
    intervalMinutes: 60,
    customPrompt: 'CROSS-BORDER LUXURY: Italija je domovina Gucci/Prada/Fendi — cene nižje. Preveri: "Originale" (original — obvezno!), "Stato" (stanje), "Certificato" (certifikat), "Polvere" (prah — originalni). Sumnjivo: "Replica", "Falso", cene pod 200€ za Gucci. Preveri avtentičnost na Vestiaire Collective ali The RealReal. Prihranek 30-50% za preprodajo.',
    tags: 'moda,luxury,gucci,prada,subito,cross-border,it',
    icon: '👜',
  },
  {
    id: 'tpl-subito-clothing',
    name: 'Premium oblačila (Armani, Stone Island) — Subito (IT→SI)',
    description: 'Italijanski premium blagovne znamke oblačila v IT do 200€. V SI 300-400€.',
    category: 'moda',
    source: 'subito',
    sourceUrl: 'https://www.subito.it/annunci-italia/vendita?q=armani+stone+island&prezzo=50-200',
    keywords: 'armani,stone island,moncler,dolce,versace',
    excludeKeywords: 'replica,falso,usato gravemente',
    minPrice: 50,
    maxPrice: 200,
    intervalMinutes: 90,
    customPrompt: 'CROSS-BORDER MODA: Italijanski premium brandi (Armani, Stone Island, Moncler) so v IT ~30% cenejši. Preveri: "Nuovo con etichetta" (novo z etiketo — najboljše!), "Originale" (original), "Taglia" (velikost). Stone Island: preveri "Penna" značko. Moncler: preveri hologram. Shipping ~15€ (več kosov skupaj se izplača).',
    tags: 'moda,premium,armani,subito,cross-border,it',
    icon: '👔',
  },
  {
    id: 'tpl-subito-bicycles',
    name: 'Ceste kolo (Pinarello, Colnago) — Subito (IT→SI)',
    description: 'Italijanska premium kolesa v IT do 1500€. V SI 2000-2500€.',
    category: 'sport',
    source: 'subito',
    sourceUrl: 'https://www.subito.it/annunci-italia/vendita?q=pinarello+colnago+bici&prezzo=500-1500',
    keywords: 'pinarello,colnago,bianchi,cannondale,cervelo',
    excludeKeywords: 'bambino,ragazzo,usato gravemente',
    minPrice: 500,
    maxPrice: 1500,
    intervalMinutes: 90,
    customPrompt: 'CROSS-BORDER PREMIUM KOLESA: Italijanska kolesa (Pinarello, Colnago, Bianchi) so v IT 20-30% cenejši. Preveri: "Taglia telaio" (velikost okvirja — preveri kompatibilnost), "Componenti" (komponente — Shimano/Campagnolo), "Peso" (teža). Pinarello: preveri serijsko številko na okvirju. Shipping kolesa je dražji (~50-80€) ampak se še vedno izplača.',
    tags: 'sport,kolo,pinarello,subito,cross-border,it',
    icon: '🚴',
  },

  // ===== WILLHABEN.AT (Avstrija — največji avstrijski oglasnik) =====
  // 5-10% cenejše za avto dele in opremo. Shipping do SI: 8-12€.
  {
    id: 'tpl-willhaben-bmw-parts',
    name: 'BMW original deli — Willhaben (AT→SI)',
    description: 'BMW original rezervni deli v AT do 300€. V SI dražji 20-30%.',
    category: 'avto',
    source: 'willhaben',
    sourceUrl: 'https://www.willhaben.at/iad/kaufen-und-verkaufen?keyword=bmw+original&priceFrom=50&priceTo=300',
    keywords: 'bmw,original,teile,ersatzteil',
    excludeKeywords: 'reparatur,defekt,nachbau',
    minPrice: 50,
    maxPrice: 300,
    intervalMinutes: 60,
    customPrompt: 'CROSS-BORDER AVTO DELI: Avstrija blizu SI, low shipping. Original BMW deli ~20% cenejši. Preveri: "Original BMW" (original — obvezno!), "Teilenummer" (številka dela — preveri kompatibilnost z BMW ETK katalogom), "Zustand" (stanje). Sumnjivo: "Nachbau" (aftermarket kopija), "Defekt". Vklopi "Original" filter. Prihranek sešteva pri večjih servisih.',
    tags: 'avto,bmw,deli,willhaben,cross-border,at',
    icon: '🔧',
  },
  {
    id: 'tpl-willhaben-ski',
    name: 'Smučarska oprema (Atomic, Head) — Willhaben (AT→SI)',
    description: 'Avstrijske smuči (Atomic, Head) v AT do 400€. V SI 500-600€. Sezonska priložnost!',
    category: 'sport',
    source: 'willhaben',
    sourceUrl: 'https://www.willhaben.at/iad/kaufen-und-verkaufen?keyword=atomic+head+ski&priceFrom=150&priceTo=400',
    keywords: 'atomic,head,rossignol,volkl,blizzard',
    excludeKeywords: 'kind,kinderski,defekt',
    minPrice: 150,
    maxPrice: 400,
    intervalMinutes: 90,
    customPrompt: 'CROSS-BORDER SEZONSKA: Avstrija = smučarska država, izbira velika in cenejša. Atomic in Head sta avstrijski znamki (direktno cenejše). Preveri: "Länge" (dolžina — preveri glede na višino), "Bindung" (vez — preveri servis), "Belag" (podloga — preveri stanje). Najboljši čase za nakup: pomlad (marec/april) ko Avstrijci prodajajo opremo. Shipping ~20€ (smuči so dolge).',
    tags: 'sport,smuci,atomic,willhaben,cross-border,at',
    icon: '⛷️',
  },
  {
    id: 'tpl-willhaben-furniture',
    name: 'IKEA / design pohištvo — Willhaben (AT→SI)',
    description: 'IKEA in design pohištvo v AT do 300€. V SI dražji 15-20%. AT ima več IKEA.',
    category: 'drugo',
    source: 'willhaben',
    sourceUrl: 'https://www.willhaben.at/iad/kaufen-und-verkaufen?keyword=ikea&priceFrom=50&priceTo=300',
    keywords: 'ikea,design,stuhl,tisch,schrank',
    excludeKeywords: 'defekt,beschädigt',
    minPrice: 50,
    maxPrice: 300,
    intervalMinutes: 120,
    customPrompt: 'CROSS-BORDER POHIŠTVO: Avstrija ima več IKEA trgovin, sekundarni trg bolj aktiven. Preveri: "Zustand" (stanje — "Sehr gut" najboljše), "Originalverpackung" (embalaža), "Farbe" (barva). IKEA artikli: preveri šifro (npr. KALLAX, BILLY) na IKEA spletni strani za primerjavo cene. Samoprevzem pogosto opcija (Avstrija blizu SI).',
    tags: 'pohistvo,ikea,willhaben,cross-border,at',
    icon: '🪑',
  },
];

export function getTemplatesByCategory(category: MonitorTemplate['category'] | 'all'): MonitorTemplate[] {
  if (category === 'all') return MONITOR_TEMPLATES;
  return MONITOR_TEMPLATES.filter(t => t.category === category);
}

export function getTemplateById(id: string): MonitorTemplate | undefined {
  return MONITOR_TEMPLATES.find(t => t.id === id);
}
